### ISSUE TITLE
Not able to run the code

### ISSUE THREAD

**Issue by deepakgarg08** [bigdata-ustc/EduData#93]
## 🐛 Description
(A clear and concise description of what the bug is.)
When i try to download or just type edudata, it gives error

### Error Message

`⚡ master ~/EduData edudata
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/edudata", line 33, in <module>
    sys.exit(load_entry_point('EduData', 'console_scripts', 'edudata')())
  File "/home/zeus/miniconda3/envs/cloudspace/bin/edudata", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/teamspace/studios/this_studio/EduData/EduData/main.py", line 9, in <module>
    from longling.ML.toolkit.dataset import train_valid_test, kfold
ModuleNotFoundError: No module named 'longling.ML'`

(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=100` before running your script.)
done

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. I just installed the dependencies "pip install -e ."
2. edudata ls

## What have you tried to solve it?

1. I tried installing longling manually, but it says already installed

## Environment

<details>
<summary>Environment Information</summary>

**Operating System:** ...
running in ubuntu (on lightening.ai)

**Python Version:** (e.g., python3.6, anaconda/python3.7, venv/python3.8)
I tried in python 3.8 and 3.9.19 version
both are giving the same error

</details>

**Comment by zjj1333** [comment]
Your logging may be too new, it is recommended to replace it with pip install longling==1.3.3

**Comment by IloveSC228** [comment]
You just need change longling.ML to longling.ml
